version: 2
registries:
  ghcr:
    type: docker-registry
    url: ghcr.io
    username: ${{secrets.GHCR_USERNAME}}
    password: ${{secrets.GHCR_TOKEN}}

  dockerhub:
    type: docker-registry
    url: registry-1.docker.io
    username: ${{secrets.DOCKERHUB_USER}}
    password: ${{secrets.DOCKERHUB_TOKEN}}

  github-maven:
    type: maven-repository
    url: https://maven.pkg.github.com/${{github.repository_owner}}/*
    username: ${{secrets.GHCR_USERNAME}}
    password: ${{secrets.GHCR_TOKEN}}
updates:
  # (Angular app)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Asia/Bangkok"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels: ["dependencies", "npm", "frontend"]
    ignore:
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]
    groups:
      angular-core:
        patterns: ["@angular/*", "zone.js"]
        update-types: ["minor", "patch"]
      tooling-and-tests:
        patterns: ["typescript", "karma*", "jasmine*", "@types/*", "cypress"]
        update-types: ["minor", "patch"]
      ui-and-md:
        patterns: ["highlight.js", "marked", "github-markdown-css", "apexcharts", "ng-apexcharts", "ngx-*"]
        update-types: ["minor", "patch"]
      codemirror-suite:
        patterns: ["codemirror", "@codemirror/*"]
        update-types: ["minor", "patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Bangkok"
    target-branch: "main"
    labels: ["dependencies", "github-actions"]
    open-pull-requests-limit: 10

  # Docker images (Nginx, Node…)
  - package-ecosystem: "docker"
    directory: "/docker"
    registries: ["ghcr", "dockerhub"]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "Asia/Bangkok"
    target-branch: "main"
    labels: ["dependencies", "docker"]
    open-pull-requests-limit: 10
    groups:
      nginx-node-base:
        patterns: ["nginx", "node"]
        update-types: ["minor", "patch"]
