version: 2
updates:
  # (Angular app)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Asia/Bangkok"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels: ["dependencies", "npm", "frontend"]
    # CHỈ chặn nâng major Angular (v21+), vẫn cho phép 20.x
    ignore:
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]
    groups:
      angular-core:
        patterns:
          - "@angular/*"
          - "zone.js"
        update-types: ["minor", "patch"]
      tooling-and-tests:
        patterns:
          - "typescript"
          - "karma*"
          - "jasmine*"
          - "@types/*"
          - "cypress"
        update-types: ["minor", "patch"]
      ui-and-md:
        patterns:
          - "highlight.js"
          - "marked"
          - "github-markdown-css"
          - "apexcharts"
          - "ng-apexcharts"
          - "ngx-*"
        update-types: ["minor", "patch"]
      codemirror-suite:
        patterns:
          - "codemirror"
          - "@codemirror/*"
        update-types: ["minor", "patch"]


  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Bangkok"
    target-branch: "main"
    labels: ["dependencies", "github-actions"]
    open-pull-requests-limit: 10

  # Docker images (Nginx, Node…)
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "Asia/Bangkok"
    target-branch: "main"
    labels: ["dependencies", "docker"]
    open-pull-requests-limit: 10
    groups:
      nginx-node-base:
        patterns:
          - "nginx"
          - "node"
        update-types: ["minor", "patch"]
      dotnet-base:
        patterns:
          - "mcr.microsoft.com/dotnet/*"
        update-types: ["minor", "patch"]
      jre-maven:
        patterns:
          - "eclipse-temurin:*"
          - "maven:*"
        update-types: ["minor", "patch"]
