# Stage 1: build Angular app
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2: serve với Nginx
FROM nginx:alpine
COPY --from=build /app/dist/codecampus /usr/share/nginx/html
# copy sẵn default nginx config nếu cần
COPY nginx.conf /etc/nginx/conf.d/default.conf
