import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ExerciseQuiz } from '../../../../core/models/exercise.model';

@Component({
  selector: 'app-exercise-details',
  imports: [CommonModule],
  templateUrl: './exercise-details.component.html',
  styleUrl: './exercise-details.component.scss',
})
export class ExerciseDetailsComponent {
  exercise: ExerciseQuiz = {
    id: 'ex1',
    userId: 'user1',
    title: 'Bài kiểm tra kiến thức cơ bản',
    description:
      'Bài kiểm tra gồm các câu hỏi trắc nghiệm về kiến thức cơ bản.',
    exerciseType: 'QUIZ',
    difficulty: 'HARD',
    orgId: 'org1',
    active: true,
    cost: 10,
    freeForOrg: false,
    startTime: '2024-06-01T00:00:00Z',
    endTime: '2024-06-10T23:59:00Z',
    duration: 30,
    allowDiscussionId: 'dis1',
    resourceIds: ['res1', 'res2'],
    tags: ['Toán', 'Lập trình', 'Cơ bản'],
    allowAiQuestion: false,
    quizDetail: {
      id: 'quiz1',
      numQuestions: 2,
      totalPoints: 20,
      currentPage: 1,
      totalPages: 1,
      pageSize: 10,
      totalElements: 2,
      questions: [
        {
          id: 'q1',
          text: 'Đâu là kết quả của 2 + 2?',
          points: 10,
          type: 'SINGLE_CHOICE',
          orderInQuiz: 1,
          options: [
            {
              id: 'o1',
              optionText: '3',
              correct: false,
              order: 'A',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o2',
              optionText: '4',
              correct: true,
              order: 'B',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o3',
              optionText: '5',
              correct: false,
              order: 'C',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o4',
              optionText: '6',
              correct: false,
              order: 'D',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
          ],
          createdBy: '',
          createdAt: '',
          updatedBy: '',
          updatedAt: '',
          deletedBy: '',
          deletedAt: '',
        },
        {
          id: 'q2',
          text: 'Biến trong lập trình là gì?',
          points: 10,
          type: 'SINGLE_CHOICE',
          orderInQuiz: 2,
          options: [
            {
              id: 'o1',
              optionText: 'Hàm',
              correct: false,
              order: 'A',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o2',
              optionText: 'Giá trị lưu trữ',
              correct: true,
              order: 'B',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o3',
              optionText: 'Câu lệnh',
              correct: false,
              order: 'C',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o4',
              optionText: 'Vòng lặp',
              correct: false,
              order: 'D',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
          ],
          createdBy: '',
          createdAt: '',
          updatedBy: '',
          updatedAt: '',
          deletedBy: '',
          deletedAt: '',
        },
        {
          id: 'q2',
          text: 'Biến trong lập trình là gì?',
          points: 10,
          type: 'SINGLE_CHOICE',
          orderInQuiz: 2,
          options: [
            {
              id: 'o1',
              optionText: 'Hàm',
              correct: false,
              order: 'A',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o2',
              optionText: 'Giá trị lưu trữ',
              correct: true,
              order: 'B',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o3',
              optionText: 'Câu lệnh',
              correct: false,
              order: 'C',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o4',
              optionText: 'Vòng lặp',
              correct: false,
              order: 'D',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
          ],
          createdBy: '',
          createdAt: '',
          updatedBy: '',
          updatedAt: '',
          deletedBy: '',
          deletedAt: '',
        },
        {
          id: 'q2',
          text: 'Biến trong lập trình là gì?',
          points: 10,
          type: 'SINGLE_CHOICE',
          orderInQuiz: 2,
          options: [
            {
              id: 'o1',
              optionText: 'Hàm',
              correct: false,
              order: 'A',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o2',
              optionText: 'Giá trị lưu trữ',
              correct: true,
              order: 'B',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o3',
              optionText: 'Câu lệnh',
              correct: false,
              order: 'C',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
            {
              id: 'o4',
              optionText: 'Vòng lặp',
              correct: false,
              order: 'D',
              createdBy: '',
              createdAt: '',
              updatedBy: '',
              updatedAt: '',
              deletedBy: '',
              deletedAt: '',
            },
          ],
          createdBy: '',
          createdAt: '',
          updatedBy: '',
          updatedAt: '',
          deletedBy: '',
          deletedAt: '',
        },
      ],
      createdBy: '',
      createdAt: '',
      updatedBy: '',
      updatedAt: '',
      deletedBy: '',
      deletedAt: '',
    },
    createdBy: '',
    createdAt: '',
    updatedBy: '',
    updatedAt: '',
    deletedBy: '',
    deletedAt: '',
  };

  getOptionLabel(index: number): string {
    return String.fromCharCode(65 + index);
  }
}
